# Gemeinsame Komponenten für erweiterte Konfiguration
# Diese Datei enthält zusätzliche Features, die die Basis-Pakete erweitern

# ESPHome Core-Konfiguration überschreiben
esphome:
  name: ${devicename}
  friendly_name: ${friendly_name}
  comment: ${device_comment}
  name_add_mac_suffix: false

# Logger-Konfiguration (INFO für normale Logs, DEBUG für Fehlersuche)
logger:
  level: INFO

# WiFi-Konfiguration überschreiben
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2  # Nur sichere Verschlüsselung akzeptieren
  # Fallback-AP wenn WiFi-Verbindung fehlschlägt
  ap:
    ssid: "${friendly_name} Fallback"
    password: !secret ap_password

# API mit Verschlüsselung überschreiben
api:
  encryption:
    key: !secret encryption_key

# Zeit von Home Assistant synchronisieren
time:
  - platform: homeassistant
    id: homeassistant_time

# OTA-Updates mit Passwort aktivieren
ota:
  - platform: esphome
    password: !secret ota_password

# MQTT-Unterstützung aktivieren
mqtt:
  broker: !secret mqtt_broker
  discovery: false
  # Topic-Präfix: Alle Geräte unter esphome/${friendly_name}
  topic_prefix: esphome/${friendly_name}

# Web-Server aktivieren
web_server:
  port: 80

# Captive Portal aktivieren (Fallback-Konfiguration bei WiFi-Problemen)
captive_portal:

# Debug-Komponente aktivieren
debug:

# Restart-Button für Fernwartung
button:
  - platform: restart
    name: "${friendly_name} Restart"
    entity_category: diagnostic

# Diagnostic-Sensoren
sensor:
  # WiFi Signal Stärke
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s
    entity_category: diagnostic

  # Betriebszeit seit letztem Neustart
  - platform: uptime
    name: "${friendly_name} Betriebszeit"
    update_interval: 60s
    entity_category: diagnostic

# Text-Sensoren
text_sensor:
  # WLAN-Konfiguration
  - platform: wifi_info
    ssid:
      name: "${friendly_name} WiFi SSID"
    bssid:
      name: "${friendly_name} WiFi BSSID"
    ip_address:
      name: "${friendly_name} IP Adresse"
    mac_address:
      name: "${friendly_name} MAC Adresse"

  # ESPHome Version
  - platform: version
    name: "${friendly_name} ESPHome Version"
    entity_category: diagnostic

  # Debug Text-Sensoren
  - platform: debug
    reset_reason:
      name: "${friendly_name} Neustart Grund"
      entity_category: diagnostic

# Binary-Sensoren
binary_sensor:
  # Verbindungsstatus
  - platform: status
    name: "${friendly_name} Status"
    entity_category: diagnostic
