# ESP32-S3 Bluetooth Proxy (Büro)

substitutions:
  devicename: "bt-proxy-buero"
  friendly_name: "BT Proxy Buero"
  device_comment: "ESP32-S3 Bluetooth Proxy"

# Packages
packages:
  # Bluetooth Proxy Package von ESPHome
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic/esp32-generic-s3.yaml@main
  # Remote extensions (API encryption, OTA, MQTT, Web Server, Captive Portal)
  common:
    url: https://github.com/legacycode-esphome/ESPHome-Config.git
    file: common.yaml
    ref: main
    refresh: 0s

# Board-Konfiguration (M5Stack AtomS3)
esp32:
  board: m5stack-atoms3
  variant: esp32s3
  framework:
    type: arduino

# MQTT Topic ohne Leerzeichen
mqtt:
  topic_prefix: esphome/${devicename}
