# Victron SmartShunt Konfiguration
# Beispielkonfiguration: https://github.com/KinDR007/VictronMPPT-ESPHOME/blob/main/smartshunt-esp8266-example.yaml

substitutions:
  # Der interne Name, der von ESPHome verwendet wird (klein, ohne Leerzeichen, Bindestriche OK)
  devicename: "smartshunt"

  # Der Anzeigename in Home Assistant (ohne Umlaute für MQTT-Kompatibilität)
  friendly_name: "SmartShunt"

  # Beschreibung, was dieses Gerät macht
  device_comment: "Victron SmartShunt Batteriemonitor"

# Remote extensions (API encryption, OTA, MQTT, Web Server, Captive Portal)
packages:
  common:
    url: https://github.com/legacycode/ESPHome-Config.git
    file: common.yaml
    ref: main
    refresh: 1d

# Board-Konfiguration (Wemos D1 Mini)
esp8266:
  board: d1_mini

# Externe Komponente für Victron
external_components:
  - source: github://KinDR007/VictronMPPT-ESPHOME@main

# UART-Konfiguration für Victron VE.Direct
uart:
  id: uart_0
  tx_pin: D6  # Nicht verwendet! Die Kommunikation ist nur lesend
  rx_pin: D7
  baud_rate: 19200
  rx_buffer_size: 256

# Victron Platform
victron:
  id: victron0
  uart_id: uart_0

# Victron Sensoren
sensor:
  - platform: victron
    victron_id: victron0
    battery_voltage:
      name: "${friendly_name} Batterie Spannung"
      icon: "mdi:battery-charging"
    auxiliary_battery_voltage:
      name: "${friendly_name} Hilfsbatterie Spannung"
      icon: "mdi:battery-outline"
    midpoint_voltage_of_the_battery_bank:
      name: "${friendly_name} Batteriebank Mittelspannung"
      icon: "mdi:battery-medium"
    midpoint_deviation_of_the_battery_bank:
      name: "${friendly_name} Batteriebank Abweichung"
      icon: "mdi:battery-alert-variant-outline"
    battery_current:
      name: "${friendly_name} Batterie Strom"
      icon: "mdi:current-dc"
    battery_temperature:
      name: "${friendly_name} Batterie Temperatur"
      icon: "mdi:thermometer"
    instantaneous_power:
      name: "${friendly_name} Momentanleistung"
      icon: "mdi:flash"
    consumed_amp_hours:
      name: "${friendly_name} Verbrauchte Ah"
      icon: "mdi:battery-minus"
    state_of_charge:
      name: "${friendly_name} Ladezustand"
      icon: "mdi:battery-70"
    time_to_go:
      name: "${friendly_name} Restlaufzeit"
      icon: "mdi:timer-outline"
    depth_of_the_deepest_discharge:
      name: "${friendly_name} Tiefste Entladung"
      icon: "mdi:battery-alert"
    depth_of_the_last_discharge:
      name: "${friendly_name} Letzte Entladung"
      icon: "mdi:battery-minus-variant"
    depth_of_the_average_discharge:
      name: "${friendly_name} Durchschnittliche Entladung"
      icon: "mdi:battery-50"
    number_of_charge_cycles:
      name: "${friendly_name} Anzahl Ladezyklen"
      icon: "mdi:counter"
    number_of_full_discharges:
      name: "${friendly_name} Anzahl Vollentladungen"
      icon: "mdi:battery-off"
    cumulative_amp_hours_drawn:
      name: "${friendly_name} Kumulierte Ah entnommen"
      icon: "mdi:battery-minus-outline"
    min_battery_voltage:
      name: "${friendly_name} Min Batterie Spannung"
      icon: "mdi:battery-low"
    max_battery_voltage:
      name: "${friendly_name} Max Batterie Spannung"
      icon: "mdi:battery-high"
    last_full_charge:
      name: "${friendly_name} Letzte Vollladung"
      icon: "mdi:battery-charging-100"
    number_of_automatic_synchronizations:
      name: "${friendly_name} Anzahl Auto-Sync"
      icon: "mdi:sync"
    number_of_low_main_voltage_alarms:
      name: "${friendly_name} Anzahl Unterspannungsalarme"
      icon: "mdi:alert-outline"
    number_of_high_main_voltage_alarms:
      name: "${friendly_name} Anzahl Ueberspannungsalarme"
      icon: "mdi:alert-outline"
    number_of_low_auxiliary_voltage_alarms:
      name: "${friendly_name} Anzahl Unterspannungsalarme Hilfs"
      icon: "mdi:alert-outline"
    number_of_high_auxiliary_voltage_alarms:
      name: "${friendly_name} Anzahl Ueberspannungsalarme Hilfs"
      icon: "mdi:alert-outline"
    min_auxiliary_battery_voltage:
      name: "${friendly_name} Min Hilfsbatterie Spannung"
      icon: "mdi:battery-low"
    max_auxiliary_battery_voltage:
      name: "${friendly_name} Max Hilfsbatterie Spannung"
      icon: "mdi:battery-high"
    amount_of_discharged_energy:
      name: "${friendly_name} Entladene Energie"
      icon: "mdi:battery-arrow-down"
      unit_of_measurement: "kWh"
      accuracy_decimals: 2
      device_class: energy
      state_class: total_increasing
      filters:
        - multiply: 0.001  # Wh → kWh
    amount_of_charged_energy:
      name: "${friendly_name} Geladene Energie"
      icon: "mdi:battery-arrow-up"
      unit_of_measurement: "kWh"
      accuracy_decimals: 2
      device_class: energy
      state_class: total_increasing
      filters:
        - multiply: 0.001  # Wh → kWh
    dc_monitor_mode_id:
      name: "${friendly_name} DC Monitor Modus ID"
      icon: "mdi:information-outline"

# Victron Text-Sensoren
text_sensor:
  - platform: victron
    victron_id: victron0
    alarm_condition_active:
      name: "${friendly_name} Alarm Bedingung"
      icon: "mdi:alarm-light"
    alarm_reason:
      name: "${friendly_name} Alarm Grund"
      icon: "mdi:alert-circle"
    model_description:
      name: "${friendly_name} Modellbeschreibung"
      icon: "mdi:information"
    firmware_version:
      name: "${friendly_name} Firmware Version"
      icon: "mdi:chip"
    device_type:
      name: "${friendly_name} Geraetetyp"
      icon: "mdi:information"
    serial_number:
      name: "${friendly_name} Seriennummer"
      icon: "mdi:identifier"
    dc_monitor_mode:
      name: "${friendly_name} DC Monitor Modus"
      icon: "mdi:monitor-dashboard"

# Victron Binary-Sensoren
binary_sensor:
  - platform: victron
    victron_id: victron0
    relay_state:
      name: "${friendly_name} Relais Status"
      icon: "mdi:electric-switch"
