# Victron SmartSolar MPPT Konfiguration
# Beispielkonfiguration: https://github.com/KinDR007/VictronMPPT-ESPHOME/blob/main/smartsolar-mppt-esp8266-example.yaml

substitutions:
  # Der interne Name, der von ESPHome verwendet wird (klein, ohne Leerzeichen, Bindestriche OK)
  devicename: "smartsolar"

  # Der Anzeigename in Home Assistant (ohne Umlaute für MQTT-Kompatibilität)
  friendly_name: "SmartSolar"

  # Beschreibung, was dieses Gerät macht
  device_comment: "Victron SmartSolar MPPT Laderegler"

# Remote extensions (API encryption, OTA, MQTT, Web Server, Captive Portal)
packages:
  common:
    url: https://github.com/legacycode-esphome/ESPHome-Config.git
    file: common.yaml
    ref: main
    refresh: 0s

# Board-Konfiguration (M5Stack AtomS3)
esp32:
  board: m5stack-atoms3
  variant: esp32s3
  framework:
    type: arduino

# Externe Komponente für Victron MPPT
external_components:
  - source: github://KinDR007/VictronMPPT-ESPHOME@main

# UART-Konfiguration für Victron VE.Direct
# Nur RX-Pin, da VE.Direct Text Protocol read-only ist
# GPIO2 wird für Remote On/Off verwendet (siehe switch unten)
uart:
  id: uart_0
  rx_pin: GPIO1
  baud_rate: 19200
  rx_buffer_size: 256

# Victron Platform
victron:
  id: victron0
  uart_id: uart_0

# Victron Sensoren
sensor:
  - platform: victron
    victron_id: victron0
    panel_voltage:
      name: "${friendly_name} Panel Spannung"
      icon: "mdi:solar-panel"
      device_class: voltage
      state_class: measurement
    panel_power:
      name: "${friendly_name} Panel Leistung"
      icon: "mdi:solar-power"
      device_class: power
      state_class: measurement
    battery_voltage:
      name: "${friendly_name} Batterie Spannung"
      icon: "mdi:battery-charging"
      device_class: voltage
      state_class: measurement
    battery_current:
      name: "${friendly_name} Batterie Strom"
      icon: "mdi:current-dc"
      device_class: current
      state_class: measurement
    yield_total:
      name: "${friendly_name} Ertrag Gesamt"
      icon: "mdi:counter"
      unit_of_measurement: "kWh"
      accuracy_decimals: 2
      device_class: energy
      state_class: total_increasing
      filters:
        - multiply: 0.001  # Wh → kWh
    yield_today:
      name: "${friendly_name} Ertrag Heute"
      icon: "mdi:solar-power"
      unit_of_measurement: "kWh"
      accuracy_decimals: 2
      device_class: energy
      state_class: total_increasing
      filters:
        - multiply: 0.001  # Wh → kWh
    yield_yesterday:
      name: "${friendly_name} Ertrag Gestern"
      icon: "mdi:solar-power"
      unit_of_measurement: "kWh"
      accuracy_decimals: 2
      device_class: energy
      state_class: total_increasing
      filters:
        - multiply: 0.001  # Wh → kWh
    max_power_today:
      name: "${friendly_name} Max Leistung Heute"
      icon: "mdi:solar-power-variant"
      device_class: power
      state_class: measurement
    max_power_yesterday:
      name: "${friendly_name} Max Leistung Gestern"
      icon: "mdi:solar-power-variant"
      device_class: power
      state_class: measurement
    day_number:
      name: "${friendly_name} Tag Nummer"
      icon: "mdi:calendar-today"
    charging_mode_id:
      name: "${friendly_name} Lademodus ID"
      icon: "mdi:information-outline"
    error_code:
      name: "${friendly_name} Fehlercode"
      icon: "mdi:alert-circle-outline"
    tracking_mode_id:
      name: "${friendly_name} Tracking Modus ID"
      icon: "mdi:information-outline"
    load_current:
      name: "${friendly_name} Last Strom"
      icon: "mdi:current-dc"
      device_class: current
      state_class: measurement

# Victron Text-Sensoren
text_sensor:
  - platform: victron
    victron_id: victron0
    charging_mode:
      name: "${friendly_name} Lademodus"
      icon: "mdi:battery-charging-100"
    tracking_mode:
      name: "${friendly_name} Tracking Modus"
      icon: "mdi:solar-panel-large"
    error:
      name: "${friendly_name} Fehler"
      icon: "mdi:alert-circle"
    firmware_version:
      name: "${friendly_name} Firmware Version"
      icon: "mdi:chip"
    device_type:
      name: "${friendly_name} Geraetetyp"
      icon: "mdi:information"
    serial_number:
      name: "${friendly_name} Seriennummer"
      icon: "mdi:identifier"

# Victron Binary-Sensoren
binary_sensor:
  - platform: victron
    victron_id: victron0
    load_state:
      name: "${friendly_name} Last Status"
      icon: "mdi:power-plug"
    relay_state:
      name: "${friendly_name} Relais Status"
      icon: "mdi:electric-switch"

# Remote On/Off Switch
# Steuert den RX-Pin des Victron SmartSolar
# HIGH (3.3V) = Ladegeraet EIN
# LOW (GND) = Ladegeraet AUS
switch:
  - platform: gpio
    pin: GPIO2  # verbunden mit Victron RX
    name: "${friendly_name} Remote On/Off"
    icon: "mdi:power"
    restore_mode: ALWAYS_ON  # Nach Neustart eingeschaltet
    inverted: false  # HIGH = EIN, LOW = AUS
